name: 'Inflate Secrets'
description: 'Inflates the secret values into the appropriate files'
inputs:
  keystore:
    description: 'The keystore to inflate'
    required: true
  google-services:
    description: 'The google-services.json to inflate'
    required: true
  playstore-creds:
    description: 'The playstore credentials to inflate'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Mock debug google-services.json
      shell: bash
      run: |
        cp .github/mock-google-services.json androdiApp/src/demo/google-services.json
        cp .github/mock-google-services.json androdiApp/src/prod/google-services.json

    - name: Inflate release_keystore.keystore
      shell: bash
      env:
        KEYSTORE: ${{ inputs.keystore }}
      run: | 
        echo $KEYSTORE | base64 --decode > androdiApp/release_keystore.keystore

    - name: Inflate google-services.json
      shell: bash
      env:
        GOOGLE_SERVICES: ${{ inputs.google-services }}
      run: |
        echo $GOOGLE_SERVICES > androdiApp/google-services.json

    - name: Inflate playStorePublishServiceCredentialsFile.json
      shell: bash
      env:
        CREDS: ${{ inputs.playstore-creds }}
      run: |
        echo $CREDS > androdiApp/playStorePublishServiceCredentialsFile.json
